letsencrypt-nginx:
  tty: true
  image: nginx:alpine
  stdin_open: true
  volumes:
    - letsencrypt-verify:/usr/share/nginx/html/
  labels:
    io.rancher.sidekicks: rancher-lets-encrypt

rancher-lets-encrypt:
  tty: true
  image: tozny/rancher-lets-encrypt
  stdin_open: true
  environment:
    DOMAINS: ${SUBDOMAINS}
    CERTBOT_EMAIL: ${EMAIL}
    STAGING: ${STAGING}
    HOST_CHECK_PORT: ${PORT}
    CERTBOT_WEBROOT: /var/www
    RENEW_BEFORE_DAYS: 14
    LOOP_TIME: 300
    HOST_CHECK_LOOP_TIME: 10
  volumes:
    - letsencrypt-verify:/var/www/
    - letsencrypt-certs:/etc/letsencrypt/
  labels:
    # if we add the container as a rancher agent, we get magical things like Rancher server URL, and access keys for F-R-E-E!
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: 'environment'
